version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333" # Map Adonis.js port
    volumes:
      - .:/usr/src/app
      - ./tmp:/usr/src/app/tmp
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0 # Ensure Adonis binds to all network interfaces
      PORT: 3333
    command: npm run dev
